apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

nameprefix: dev-

configMapGenerator:
  - name: demo-backend-config
    literals:
      - ENV=dev

patches: 
  - target: 
      kind: Deployment
      name: demo-backend-deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: krishp234/demo-backend:v3
